services:
  typesense_api_sharding:
    container_name: typesense_api_sharding
    build: .
    volumes:
      - .:/app
    ports:
      - 5556:8000 
    env_file:
      - .env
    networks:
      global-net:

networks:
  global-net:
    external: true
